### ISSUE TITLE
Consider changing validation colors for gray boxes in questionnaire editor

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#521]
The colors we use for validation errors in normal steps don't seem to produce sane contrast when combined with "Error messages" and "Quota completed messages" because they are darker.

@jkicillof could you review this? @Mscebba would you update `_ncd.scss` if @jkicillof suggests an alternative? 

There's a SCSS snippet that reuses the regular validation colors, which could be modified should Jony suggest better colors: 

```css
&.dark {
    border: none;
    li .card {
      border-radius: 3px;
      @extend .grey;
      .card-content.closed-step {
        a, i {
          @extend .white-text;
        }
        .text-error {
          @extend .text-error;
        }
      }
    }
  }
```

<img width="801" alt="screen shot 2017-01-10 at 10 49 27 am" src="https://cloud.githubusercontent.com/assets/651693/21812499/e95c9aba-d731-11e6-923a-11ffdf2e3f86.png">

<img width="422" alt="screen shot 2017-01-09 at 5 29 22 pm" src="https://cloud.githubusercontent.com/assets/651693/21812500/e95e6e26-d731-11e6-88e9-9025b451c7fa.png">
