### ISSUE TITLE
When downloading audio, the downloaded file has a guid name and no extension

### ISSUE THREAD

**Issue by nekron** [instedd/ask#629]
<img width="858" alt="screen shot 2017-02-09 at 4 07 03 pm" src="https://cloud.githubusercontent.com/assets/957103/22798725/d47079a6-eee1-11e6-9035-d1c35b010d31.png">
<img width="250" alt="screen shot 2017-02-09 at 4 07 31 pm" src="https://cloud.githubusercontent.com/assets/957103/22798747/e31d93b2-eee1-11e6-93db-25ee07eaa389.png">

**Comment by waj** [comment]
This is not a feature we implemented on purpose. Apparently a new version of Chrome comes with this option. Let's see if that button can be disabled.

**Comment by asterite** [comment]
It was introduced in Chrome 55: https://bugs.chromium.org/p/chromium/issues/detail?id=675596&can=2&q=media%20download&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

The "fix" is to add this to the CSS:

```css 
video::-internal-media-controls-download-button {
    display:none;
}

video::-webkit-media-controls-enclosure {
    overflow:hidden;
}

video::-webkit-media-controls-panel {
    width: calc(100% + 30px); /* Adjust as needed */
}
```
